TestWebApp/TestWebApp/Controllers/RNDController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using DomainClass.Entity;
using TestWebApp.Models;
using DomainClass;

namespace TestWebApp.Controllers
{
  public class RNDController : Controller
  {
    // GET: RND
    public ActionResult Index()
    {
      List<Contact> Contacts = new List<Contact>();
      Contacts.Add(new Contact() { Id = 1, FirstName = "one", LastName = "one", Email = "one@one" });
      Contacts.Add(new Contact() { Id = 2, FirstName = "two", LastName = "two", Email = "two@two" });
      Contacts.Add(new Contact() { Id = 3, FirstName = "three", LastName = "three", Email = "three@three" });
      Contacts.Add(new Contact() { Id = 4, FirstName = "four", LastName = "four", Email = "four@four" });

      var rndModelView = new RndModelView();
      rndModelView.Id = 21;
      rndModelView.Name = "AccountName";
      rndModelView.ContactSelectId.Add(2);
      rndModelView.ContactSelectId.Add(3);
      rndModelView.NewContacts = Contacts; //newContacts=AllContacts

      return View(rndModelView);
    }
  }
}

TestWebApp/TestWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>



    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script src="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js"
            type="text/javascript"></script>
    <link href="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css"
          rel="stylesheet" type="text/css" />
    
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Account", "Index", "Account")</li>
                    <li>@Html.ActionLink("Contact", "Index", "Contact")</li>
                    <li>@Html.ActionLink("R&D", "Index", "RND")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    
    
    @RenderSection("scripts", required: false)
</body>
</html>